config/routes.rb
Rails.application.routes.draw do

 match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

 resources :password_resets, only: [:new, :create, :edit, :update]
  get "/home" => "welcome#index"

  get "/about" => "welcome#about", as: :about_us

  get  "/contact_us" => "contact_us#new"
  post "/contact_us" => "contact_us#create" # this will have the same helper

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :questions do

    resources :answers, only: [:create, :destroy, :edit, :update]

    resources :likes, only: [:create, :destroy]

    resources :votes, only: [:create, :update, :destroy]
  end

  root "welcome#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  # by having this `belongs_to` in the model we can easily fetch the question
  # for a given answer by running:
  # ans = Answer.find(14)
  # q   = ans.question
  # belongs_to assumes that the `answers` table has a foreign_key called
  # question_id (Rails convention)
  belongs_to :question
  belongs_to :user

  validates :body, presence: true


  def user_full_name
    user ? user.full_name : ""
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question
  before_action :find_and_authorize_answer, only: :destroy

  #include QuestionsAnswersHelper
  #helper_method :user_like

  def create
    answer_params    = params.require(:answer).permit(:body)
    @answer          = Answer.new answer_params
    @answer.question = @question
    @answer.user     = current_user
    respond_to do |format|
      if @answer.save
        AnswersMailer.notify_question_owner(@answer).deliver_later
        format.html { redirect_to question_path(@question), notice: "Thanks for answering" }
        #format.js { render js: "alert('success');" }
        format.js { render :create_success }
      else
        flash[:alert] = "not saved"
        # this will render the show.html.erb inside views/questions
        #render "/questions/show"
        format.html { render "/questions/show" }
        format.js { render :create_failure}
      end
    end
  end

  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to question_path(@question), notice: "Answer deleted!" }
      format.js { render }
    end
  end

  def edit
    @answer = Answer.find params[:id]
  end

  private

  def find_question
    @question = Question.friendly.find params[:question_id]
  end

  def find_and_authorize_answer
    #head will stop the HTTP request and send
    @answer = @question.answers.find params[:id]
    redirect_to root_path unless can? :destroy, @answer
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<%# dom_id is used to generate a unique HTML id for elements from an ActiveRecord
    object. It uses the object type and its id to generate a unique id. %>
<div id="<%= dom_id(answer) %>" style="<%= style if defined?(style) %>">
  <%= answer.body %>
  by: <%= answer.user_full_name.titleize %>
  <% if can? :destroy, answer %>
    <%= link_to "delete", question_answer_path(@question, answer),
                          data: {confirm: "Are you sure?"},
                          method: :delete,
                          remote: true %>
  <% end %>
  <% if can? :edit, answer %>
    <%= link_to "Edit", edit_question_answer_path(@question, answer),
                        remote: true,
                        data: {toggle: "modal", target: "#edit-answer"},
                        class: "btn btn-primary btn-sm" %>
    <!-- Button trigger modal -->
  <% end %>
  <hr>
</div>

app/views/answers/_form.html.erb
<%#= we switch the @ answer below to be just answer %>
<%= answer.errors.full_messages.join(", ") %>
<%#= form_for @answer, url: question_answers_path(@question) do |f| %>
<%# adding a remote: true option to the form makes it so that the form submits
    with AJAX (prevent the default as well) %>
<%= simple_form_for [@question, answer], remote: true do |f|  %>
<%#= form_for [@question, @answer] do |form_helper|  %>
  <%= f.input :body, label: false %>
  <%= f.submit data: {disable_with: "submitting..."}, class: "btn btn-primary" %>
<% end %>

app/views/answers/create_failure.js.erb
$("#answer-form").html("<%= j render '/answers/form', answer: @answer %>");

app/views/answers/create_success.js.erb
// in this context we are @answer is the instance variable from the answer_controller
$("#answers").prepend("<%= j render '/answers/answer', answer: @answer, style: 'display: none' %>");
//$("#answer_body").val("");
//<%# @answer = Answer.new %>
$("#answer-form").html("<%= j render '/answers/form', answer: Answer.new %>");
$("#<%= dom_id(@answer) %>").slideDown(1000);

app/views/answers/destroy.js.erb
$("#<%= dom_id(@answer) %>").fadeOut(1000, function(){
  $(this).remove();
});

app/views/answers/edit.js.erb
$("#edit-answer").html("<%= j render 'modal_form' %>");